apiVersion: v1
kind: Service
metadata:
  name: banking-frontend-service
spec:
  type: ClusterIP
  ports:
    -   port: 80
        targetPort: 80
  selector:
    app: banking-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
  labels:
    app: banking-frontend
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 10s"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
    spec:
      imagePullSecrets:
        -   name: ghcrregistrypullsecret
      containers:
        -   name: banking-app
            imagePullPolicy: Always
            image: ghcr.io/oryono/banking-tailwind:latest
            ports:
              -   containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: banking-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    -   hosts:
          - alpinebanking.software
        secretName: alpinebanking-software-secret
  rules:
    -   host: "*.alpinebanking.software"
        http:
          paths:
            -   backend:
                  serviceName: banking-frontend-service
                  servicePort: 80
